---
title: "LIS4370 -- Mod 4"
author: "Alina Hagen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup,}
# Creating the data frame
Frequency <- c(0.6, 0.3, 0.4, 0.4, 0.2, 0.6, 0.3, 0.4, 0.9, 0.2)
BP <- c(103, 87, 32, 42, 59, 109, 78, 205, 135, 176)
First <- c(1, 1, 1, 1, 0, 0, 0, 0, NA, 1)
Second <- c(0, 0, 1, 1, 0, 0, 1, 1, 1, 1)
FinalDecision <- c(0, 1, 0, 1, 0, 1, 0, 1, 1, 1)

# Creating the data frame
hospital_data <- data.frame(Frequency, BP, First, Second, FinalDecision)

```


```{r}
library(gridExtra)
library(ggplot2)

p1<- ggplot(hospital_data, aes(x = factor(First), y = BP)) +
  geom_boxplot() +
  scale_x_discrete(labels = c("0" = "No Immediate Concern", "1" = "Needs Attention")) +
  labs(title = "BP Across First Assessment by General Doctor",
       x = "First Assessment",
       y = "Blood Pressure")
  
p2<- ggplot(hospital_data, aes(x = factor(Second), y = BP)) +
  geom_boxplot() +
  scale_x_discrete(labels = c("0" = "Low Risk", "1" = "High Risk")) +
  labs(title = "BP Across Second Assessment by External Doctor",
       x = "Second Assessment",
       y = "Blood Pressure")

p3<- ggplot(hospital_data, aes(x = factor(FinalDecision), y = BP)) +
  geom_boxplot() +
  scale_x_discrete(labels = c("0" = "Low Priority", "1" = "High Priority")) +
  labs(title = "BP Across Immediate Care Final Decision",
       x = "Final Decision",
       y = "Blood Pressure")

grid.arrange(p1,p2,p3, ncol = 3)

```
``` {r}
ggplot(hospital_data, aes(x = Frequency, fill = factor(FinalDecision))) +
  geom_histogram(binwidth = 0.1, position = "stack", color = "black") +
  scale_fill_manual(
    values = c("0" = "darkolivegreen3", "1" = "tomato"),
    labels = c("0" = "Low Priority", "1" = "High Priority"),
    name = "Final Decision"
  ) +
  labs(
    title = "Distribution of Hospital Visit Frequency by Final Decision",
    x = "Visit Frequency",
    y = "Count")
```







